# Build settings
# Gems
gems: 
- jekyll-paginate
- jekyll-feed

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
#url: "http://rafalib.github.io"
#baseurl: "/"
url: "https://alfonsnavarro.github.io/navarrolab"
enforce_ssl: ""
baseurl: "/"

# Title of website
title: Molecular Oncology and Embryology lab

#Default keywords (used if no keywords are specified on a page basis)
keywords: Navarro, Alfons, Molecular Oncology and Embryology lab, non-coding RNAs, microRNAs, lncRNAs, piwiRNAs, exosomes, NSCLC

# Short description of your site
desc: Sample Description

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar.jpg"

# List of links in the navigation bar
nav-links:
    Home: ""
    #About: "pages/about.html"
    People: "pages/people.html"
    Research: "pages/research.html"
    Books: "pages/books.html"
    #Software: "web_page/pages/software.html"
    #Teaching: "web_page/pages/teaching.html"
    #News: "pages/news.html"
    #Grants: "pages/grants.html"
# --- Footer options --- #

# If the values are empty, they are ignored 
profile:
  name: Alfons Navarro
  email: anavarroponz@ub.edu
  facebook: 
  github: AlfonsNavarro
  twitter: anavarroponz
  linkedin: 
  stackoverflow: 

# To display link in the footer section
pretty-url: "bchetty.com"

# --- Misc --- #

# Your Disqus profile (shortname) settings
disqus: 

# Google Analytics Settings
google_analytics: UA-151564720-1

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Spain"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Babji, Chetty
creator-url: https://bchetty.com

theme: jekyll-theme-dinky
